apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: myapp
          image: nginx:latest
          ports:
            - containerPort: 80
          readinessProbe:
# Проверка готовности приема трафика по 80 порту.         
            tcpSocket:
              port: 80
            failureThreshold: 40
            periodSeconds: 1
# Проверка доступности и жизнеспособности контейнера, который находится на 80 порту.
          livenessProbe:
            tcpSocket:
              port: 80
            failureThreshold: 40
            periodSeconds: 1
# Проверка работоспособности приложения
          startupProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            failureThreshold: 40
            periodSeconds: 1
          resources:
            limits:
              cpu: 500m
# Для того, что бы дать время для запуска нового пода              
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - web
              topologyKey: "kubernetes.io/hostname" 
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: myapp-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myapp
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Pods
      pods:
        metric:
          name: pods-cpu
        target:
          type: AverageValue
          averageValue: 1k
          
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 128Mi
