apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: myapp
          image: myapp:latest
          ports:
            - containerPort: 8080
          readinessProbe:
# Проверка готовности приема трафика по 8080 порту.         
            tcpSocket:
              port: 8080
            failureThreshold: 40
            periodSeconds: 1
# Проверка доступности и жизнеспособности контейнера, который находится на 8080 порту.
          livenessProbe:
            tcpSocket:
              port: 8080
            failureThreshold: 40
            periodSeconds: 1
# Проверка работоспособности приложения
          startupProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            failureThreshold: 40
            periodSeconds: 1
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 100m
              memory: 128Mi
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - web
              topologyKey: "kubernetes.io/hostname" 
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: myapp-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myapp
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
